### ISSUE TITLE
Create List Recommendations Feature Page

### ISSUE THREAD

**Issue by brianshao-prog** [American-Capstones/TAMU-Spring-2022#8]
### Pre-requisites

- [x] I looked through both [open and closed issues](../issues?utf8=✓&q=is%3Aissue) and did not find an existing bug.

### Is your feature request related to a problem? Please describe.

Currently, no page exists for displaying a list of recommended flights along with their respective links. Need to fulfill MVP 1.

### Describe the solution you'd like

- Create the folder for the landing page in `\packages\web\src\pages\recommendations`
- Create a file in the above folder titled `index.tsx`
- Put text saying that this is the recommendations page!
- Within recommendations page, put table/list data structure
- Within recommendations page, populate table/list data structure with each item displaying a hyperlink to a miscellaneous AA flight

**Comment by gageayk** [comment]
Finished
